name: Build and deploy Docker app to Azure
on:
  push:
    branches:
      - main
env:
  AZURE_WEBAPP_NAME: azure-web-app-for-containers-test
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set env vars
        run: |
          IMAGE_PATH=ghcr.io/${{ github.repository }}
          IMAGE_PATH=$(echo ${IMAGE_PATH} | tr '[A-Z]' '[a-z]')
          echo "IMAGE_PATH=${IMAGE_PATH}" >> ${GITHUB_ENV}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t ${IMAGE_PATH}:release .
      - name: Docker login
        run: echo "${{ secrets.GCR_TOKEN }}" | docker login https://ghcr.io -u ${{ secrets.GCR_USERNAME }} --password-stdin
      - name: Docker push
        run: docker push ${IMAGE_PATH}:release
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set env vars
        run: |
          IMAGE_PATH=ghcr.io/${{ github.repository }}
          IMAGE_PATH=$(echo ${IMAGE_PATH} | tr '[A-Z]' '[a-z]')
          echo "IMAGE_PATH=${IMAGE_PATH}" >> ${GITHUB_ENV}
      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set Web App GCR authentication
        uses: Azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }} 
          app-settings-json: |
            [
              {
                "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                "value": "${{ secrets.GCR_TOKEN }}",
                "slotSetting": false
              },
              {
                "name": "DOCKER_REGISTRY_SERVER_URL",
                "value": "https://ghcr.io",
                "slotSetting": false
              },
              {
                "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                "value": "${{ secrets.GCR_USERNAME }}",
                "slotSetting": false
              },
              {
                "name": "WEBSITES_PORT",
                "value": "3000",
                "slotSetting": false
              }
            ]
      - name: Deploy to Azure Web App for Container
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} 
          images: ${{ env.IMAGE_PATH }}:release
